# Dockerfile para Backend Django
FROM python:3.9-slim

# Diretório de trabalho
WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código
COPY . .

# Expor a porta do Django
EXPOSE 8000

# Comando para iniciar o Django
CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:8000"]
